name: gnn_tutorial
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - matplotlib
  - ipympl
  - lxml
  - scikit-learn
  - python-igraph
  - cairocffi
  - versioningit
  - pre-commit
  - pytest
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torch-geometric
    - torch-geometric-temporal
